services:
  - type: web
    name: axio-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /index.php
    envVars:
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ZXphpOdvSasraMtvkOsRCMybUOquiAmN
